"""Paper 2's tables, generated from the recorded data (loop0008 item 08).

    python -m paper2.latex.make_tables          # writes paper2/latex/tables/*.tex

Reads only; writes nothing outside `paper2/latex/tables/`. Every table the
LaTeX draft inputs from `tables/` comes from here, and each file says in a
comment which records it was made from.

- `names.tex`        section 2: name usage and citations (`paper2.section2_figures.numbers`,
                     from the OpenAlex caches of 2026-09-29);
- `periods.tex`      section 3: relevant works per period, 2005-2024, for the three most
                     used names (same source);
- `communities.tex`  section 3: works citing the Linhares-Yanasse papers, by discipline cited
                     (same source, the citation cache of 2026-09-29);
- `cost.tex`         section 4: nodes, repaired against published rules
                     (`paper2/data/solver_fix_cost_{mosp40,cs,cs125,pw}.csv`);
- `split.tex`        section 4: the re-certifications of the root split
                     (`paper2/data/solver_fix_split_{tasks,results}.csv`, read as they are now);
- `certificates.tex` section 4: certificates under the repaired rules
                     (`paper2/data/certificates/repaired.csv`);
- `dataset.tex`      section 4: the dataset by collection
                     (`paper2/data/dataset/classes.csv.gz`, `index.csv.gz`).
"""

from __future__ import annotations

import csv
import statistics
import gzip
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "paper2" / "data"
OUT = Path(__file__).resolve().parent / "tables"

DONE = {"sat", "unsat"}


def _n(x: int) -> str:
    """An integer with thin-space-free comma thousands, as the prose has it."""
    return f"{x:,}"


def _write(name: str, source: str, body: list[str]) -> str:
    OUT.mkdir(exist_ok=True)
    text = "\n".join([f"% Generated by python -m paper2.latex.make_tables. Source: {source}.",
                      "% Do not edit by hand.", *body]) + "\n"
    (OUT / name).write_text(text)
    return text


# --- section 2 -------------------------------------------------------------

ORDER = [  # (key in numbers()["names"], printed name, Table 1 ref keys, discipline)
    ("graph path-width", "Pathwidth", ["13"], "graph theory"),
    ("gate matrix layout", "Gate matrix layout", ["6", "8"], "VLSI"),
    ("PLA folding", "PLA folding", ["6"], "VLSI"),
    ("MOSP", "MOSP", ["1", "4"], "operations research"),
    ("vertex separation", "Vertex separation", ["13"], "graph theory"),
    ("edge search game", "Edge search", ["10"], "graph theory"),
    ("node search game", "Node search", ["9"], "graph theory"),
    ("one-dimensional logic", "One-dimensional logic", ["7"], "VLSI"),
    ("interval thickness", "Interval thickness", ["5"], "graph theory"),
    ("narrowness", "Narrowness", ["11"], "graph theory"),
    ("split bandwidth", "Split bandwidth", ["12"], "graph theory"),
    ("edge separation", "Edge separation", ["14"], "graph theory"),
]
CITE = {"1": "Yanasse1997b", "4": "LY2002ref4", "5": "LY2002ref5", "6": "LY2002ref6",
        "7": "LY2002ref7", "8": "LY2002ref8", "9": "LY2002ref9", "10": "LY2002ref10",
        "11": "LY2002ref11", "12": "LY2002ref12", "13": "LY2002ref13", "14": "LY2002ref14"}


def names_table() -> str:
    from paper2.section2_figures import QUERIES, numbers
    num = numbers()
    disc_of = {k: d for k, _, d, _ in QUERIES}
    words = {"GT": "graph theory", "VLSI": "VLSI", "OR": "operations research"}
    n, cited = num["names"], num["cited_by"]
    rows = []
    for key, label, refs, _ in ORDER:
        disc = words[disc_of[key]]
        c = " / ".join(_n(cited[r]) if r in cited else "--" for r in refs)
        src = "; ".join(f"\\citet{{{CITE[r]}}}" for r in refs)
        rel = _n(n[key]["relevant"])
        if key == "graph path-width":
            rel += "$^{a}$"
        rows.append(f"{label} & {disc} & {rel} & {_n(n[key]['hits'])} & {src} & {c} \\\\")
    pw = n["graph path-width"]
    small = sum(v["relevant"] for k, v in n.items() if k != "graph path-width")
    body = [
        "\\begin{tabular}{@{}llrrp{4.6cm}r@{}}",
        "\\toprule",
        "Problem & Discipline & Relevant & Hits & Reference in the 2002 table & Citations \\\\",
        "\\midrule", *rows, "\\midrule",
        f"All twelve & & {_n(pw['relevant'] + small)} & {_n(num['hits_total'])} & & \\\\",
        "\\bottomrule", "\\end{tabular}",
        f"% check: other eleven = {small}; pathwidth distinct = {pw['distinct']}; "
        f"fetched {num['candidates_fetched']}, citations {num['citations_fetched']}",
    ]
    return _write("names.tex", "paper2.section2_figures.numbers() (OpenAlex caches, "
                  f"{num['candidates_fetched']})", body)


def periods_table() -> str:
    """Section 3: relevant works per period for the three most used names since 2005."""
    from paper2.section2_figures import numbers
    num = numbers()
    per = num["periods_2005_24"]
    rows = []
    for key, label in (("graph path-width", "Pathwidth"), ("MOSP", "MOSP"),
                       ("vertex separation", "Vertex separation")):
        v = per[key]
        rows.append(f"{label} & " + " & ".join(_n(x) for x in v) + f" & {_n(sum(v))} \\\\")
    rest = sorted(((sum(v), k) for k, v in per.items()
                   if k not in ("graph path-width", "MOSP", "vertex separation")), reverse=True)
    body = ["\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
            "Name & 2005--09 & 2010--14 & 2015--19 & 2020--24 & 2005--24 \\\\", "\\midrule",
            *rows, "\\bottomrule", "\\end{tabular}",
            "% check: next names over 2005-24: " + ", ".join(f"{k} {t}" for t, k in rest[:3])]
    return _write("periods.tex", "paper2.section2_figures.numbers()[\"periods_2005_24\"] "
                  "(paper2.trends.binned on the OpenAlex trend cache)", body)


def communities_table() -> str:
    """Section 3: works citing the Linhares-Yanasse papers, by the disciplines they cite."""
    from paper2.section2_figures import numbers
    num = numbers()
    sets = num["discipline_sets"]
    word = {"GT": "graph theory", "VLSI": "VLSI", "OR": "operations research"}
    rows = []
    for d in ("OR", "VLSI", "GT"):
        cites_d = {k: v for k, v in sets.items() if d in k.split("+")}
        cells = [_n(sum(cites_d.values()))]
        for e in ("OR", "VLSI", "GT"):
            cells.append("--" if e == d else _n(sum(v for k, v in cites_d.items() if e in k.split("+"))))
        rows.append(f"{word[d]} & " + " & ".join(cells) + " \\\\")
    body = ["\\begin{tabular}{@{}lrrrr@{}}", "\\toprule",
            "& & \\multicolumn{3}{c}{\\dots\\ of which also cite} \\\\",
            "\\cmidrule(l){3-5}",
            "Works citing & All & operations research & VLSI & graph theory \\\\",
            "\\midrule", *rows, "\\bottomrule", "\\end{tabular}",
            "% check: by set of disciplines cited: "
            + ", ".join(f"{k} {v}" for k, v in sorted(sets.items(), key=lambda x: -x[1]))
            + f"; citing works {num['citing_works']}"]
    return _write("communities.tex", "paper2.section2_figures.numbers()[\"discipline_sets\"] "
                  f"(OpenAlex citation cache, {num['citations_fetched']})", body)


# --- section 4: cost -------------------------------------------------------

def _mosp_pairs(stage: str, config: str):
    d = defaultdict(dict)
    with open(DATA / f"solver_fix_cost_{stage}.csv") as f:
        for r in csv.DictReader(f):
            if r["config"] == config:
                d[(r["instance_name"], r["k"])][r["setting"]] = r
    total = both = 0
    old = rep = 0
    worst = 0.0
    for v in d.values():
        if len(v) < 2:
            continue
        total += 1
        o, r = v["old"], v["repaired"]
        if o["status"] in DONE and r["status"] in DONE:
            both += 1
            old += int(o["nodes"])
            rep += int(r["nodes"])
            if int(o["nodes"]):
                worst = max(worst, int(r["nodes"]) / int(o["nodes"]))
    return total, both, old, rep, worst


def _pw_pairs():
    rows = list(csv.DictReader(open(DATA / "solver_fix_cost_pw.csv")))
    # a job writes its two rows together; the pair is the row order (as solver_fix_cost_tables)
    total = both = old = rep = 0
    for i in range(0, len(rows), 2):
        a, b = rows[i], rows[i + 1]
        assert {a["setting"], b["setting"]} == {"old", "repaired"}
        o, r = (a, b) if a["setting"] == "old" else (b, a)
        total += 1
        if o["proof"] in ("refutation", "bound") and r["proof"] in ("refutation", "bound"):
            both += 1
            old += int(o["nodes"])
            rep += int(r["nodes"])
    return total, both, old, rep


def cost_table() -> str:
    # configurations: `default` = base rules, `csearch` = base plus the better move
    # where the instance has at most five products per customer (Section 5.1)
    lines = ["\\multicolumn{7}{@{}l}{\\emph{Open stacks: one refutation of the optimum minus one per pair}} \\\\"]
    for stage, config, label, size in [
        ("mosp40", "default", "MOSP corpus, base", "9--40"),
        ("mosp40", "csearch", "MOSP corpus, with better move", "9--40"),
        ("cs", "csearch", "Chu \\& Stuckey, with better move", "50--100"),
        ("cs125", "csearch", "Chu \\& Stuckey, cap $2\\times10^8$ nodes", "125"),
    ]:
        total, both, old, rep, worst = _mosp_pairs(stage, config)
        lines.append(f"\\quad {label} & {size} & {_n(both)} of {_n(total)} & {_n(old)} & {_n(rep)} & "
                     f"{rep / old:.5f} & {worst:.3f} \\\\")
    total, both, old, rep = _pw_pairs()
    lines.append("\\addlinespace")
    lines.append("\\multicolumn{7}{@{}l}{\\emph{Graph pathwidth: one whole descent per pair, 120\\,s each}} \\\\")
    lines.append(f"\\quad VSPLIB, colouring, named, 500 Rome & 4--2{{,}}916 & {_n(both)} of {_n(total)} & "
                 f"{_n(old)} & {_n(rep)} & {rep / old:.3f} & -- \\\\")
    body = ["\\begin{tabular}{@{}llrrrrr@{}}", "\\toprule",
            "Instances & Vertices & Pairs finished & Nodes, published & Nodes, repaired & "
            "Total ratio & Largest pair ratio \\\\", "\\midrule", *lines, "\\bottomrule", "\\end{tabular}"]
    return _write("cost.tex", "paper2/data/solver_fix_cost_{mosp40,cs,cs125,pw}.csv", body)


# --- section 4: the root split ----------------------------------------------

def split_table() -> str:
    from paper2.solver_fix_split import RESULTS, TASKS, _read_rows, targets
    rows = _read_rows(TASKS)
    finished = {r["instance_name"]: r for r in _read_rows(RESULTS)}
    from paper2.solver_fix_split import EXTRA
    seen: list[str] = []
    extra = {r["instance"] for r in _read_rows(EXTRA)}
    lines = []
    for t in targets():
        name = t["instance_name"]
        if name in extra and not any(name2 in extra for name2 in seen):
            lines.append("\\midrule")
        seen.append(name)
        mine = [r for r in rows if r["instance_name"] == name and int(r["k"]) == t["k"]]
        done = [r for r in mine if r["kind"] == "task" and r["status"] == "unsat"]
        secs = sum(float(r["seconds"] or 0) for r in mine)
        if name in finished:
            state, nodes = "refuted", int(finished[name]["total_nodes"])
        else:
            state = "in flight" if mine else "not started"
            nodes = sum(int(r["nodes"]) for r in done)
        mant, exp = f"{nodes:.2e}".split("e")
        lines.append(f"\\texttt{{{name.replace('_', chr(92) + '_')}}} & {t['value']} & {t['k']} & {state} & {_n(len(done))} & "
                     f"${mant}\\times10^{{{int(exp)}}}$ & {secs / 3600:.1f} \\\\")
    stamp = max((r.get("finished") or r.get("time") or "" for r in rows), default="")
    body = ["\\begin{tabular}{@{}lrrlrrr@{}}", "\\toprule",
            "Instance & Value & $k$ & State & Tasks refuted & Nodes & Core-hours \\\\",
            "\\midrule", *lines, "\\bottomrule", "\\end{tabular}",
            f"% read {datetime.now():%Y-%m-%d %H:%M}; last task stamp {stamp}"]
    return _write("split.tex", "paper2/data/solver_fix_split_{tasks,results}.csv, "
                  f"read {datetime.now():%Y-%m-%d %H:%M}", body)


# --- section 4: certificates -------------------------------------------------

BANDS = [(9, 10), (11, 20), (21, 30), (31, 40), (41, 50), (51, 60), (61, 75)]


def certificates_table() -> str:
    """Seven columns, one configuration (`csearch`, "with better move") in the
    table; totals for both configurations in trailing comments."""
    rows = list(csv.DictReader(open(DATA / "certificates" / "repaired.csv")))
    med = lambda v: statistics.median(v) if v else 0  # noqa: E731
    lines = []
    for lo, hi in BANDS:
        x = [r for r in rows if r["config"] == "csearch" and lo <= int(r["n"]) <= hi]
        if not x:
            continue
        ref = [r for r in x if r["status"] == "unsat"]
        ok = [r for r in ref if r["check_ok"] == "True"]
        rej = [r for r in ref if r["check_ok"] == "False"]
        gz = sorted(int(r["gz_bytes"]) for r in ref)
        ms = sorted(1000 * float(r["check_seconds"]) for r in ref)
        lines.append(f"{lo}--{hi} & {_n(len(x))} & {_n(len(ok))} & {len(rej)} & "
                     f"{_n(len(x) - len(ref))} & {_n(round(med(gz)))} & {med(ms):.2f} \\\\")
    tot = Counter()
    for r in rows:
        c = r["config"]
        tot[(c, "n")] += 1
        tot[(c, "ok")] += r["check_ok"] == "True"
        tot[(c, "rej")] += r["status"] == "unsat" and r["check_ok"] == "False"
        if r["check_ok"] == "True":
            tot[(c, "gz")] += int(r["gz_bytes"])
            tot[(c, "s")] += float(r["check_seconds"])
            tot[(c, "nodes")] += int(r["nodes"])
    body = ["\\begin{tabular}{@{}lrrrrrr@{}}", "\\toprule",
            "Customers & Instances & Verified & Rejected & Not emitted & "
            "Median size (bytes, gzip) & Median check (ms) \\\\",
            "\\midrule", *lines, "\\bottomrule", "\\end{tabular}"]
    for c in ("csearch", "default"):
        body.append(f"% total {c}: {tot[(c, 'ok')]} of {tot[(c, 'n')]} verified, "
                    f"{tot[(c, 'rej')]} rejected, {tot[(c, 'gz')] / 1e6:.2f} MB gz, "
                    f"{tot[(c, 's')]:.1f} s, {tot[(c, 'nodes')]} nodes")
    return _write("certificates.tex", "paper2/data/certificates/repaired.csv", body)


# --- section 4: dataset ------------------------------------------------------

def dataset_table() -> str:
    with gzip.open(DATA / "dataset" / "index.csv.gz", "rt") as f:
        idx = list(csv.DictReader(f))
    with gzip.open(DATA / "dataset" / "classes.csv.gz", "rt") as f:
        cls = list(csv.DictReader(f))
    files = Counter(r["collection"] for r in idx)
    distinct = defaultdict(set)
    for r in idx:
        distinct[r["collection"]].add(r["cls"])
    order = list(dict.fromkeys(r["collection"] for r in idx))
    prov = defaultdict(Counter)
    for c in cls:
        p = c["provenance"] or "none"
        if c["witness"] != "1" and p != "none":
            p = "nowit"
        prov[c["owner"]][p] += 1
    lines = []
    tot = Counter()
    for col in order:
        p = prov[col]
        new = sum(p.values())
        row = [files[col], len(distinct[col]), new, p["certified:refutation"],
               p["certified:bound"], p["solution"], p["nowit"] + p["none"]]
        for i, v in enumerate(row):
            if i != 1:
                tot[i] += v
        label = col.replace("&", "\\&")
        if "second copy" in col:
            label += "$^{a}$"
        lines.append(f"{label} & " + " & ".join(_n(v) for v in row) + " \\\\")
    lines.append("\\midrule")
    lines.append("All & " + " & ".join("" if i == 1 else _n(tot[i]) for i in range(7)) + " \\\\")
    body = ["\\begin{tabular}{@{}lrrrrrrr@{}}", "\\toprule",
            " & & & & \\multicolumn{2}{c}{Certified} & & \\\\",
            "\\cmidrule(lr){5-6}",
            "Collection & Files & Classes & Counted here & by search & by bound & Upper bound only & "
            "No witnessed value \\\\", "\\midrule", *lines, "\\bottomrule", "\\end{tabular}"]
    return _write("dataset.tex", "paper2/data/dataset/{index,classes}.csv.gz", body)


def main() -> None:
    for f in (names_table, periods_table, communities_table, cost_table, split_table, certificates_table, dataset_table):
        text = f()
        print(text.splitlines()[0])


if __name__ == "__main__":
    main()
